OriginalCard.create!({"id" => 743, "name" => "alex calderon", "cardtype" => "Gold", "approved" => true, "api_id" => "slwxsyzrjzuhrgksfm1x", "season" => 23})
OriginalCard.create!({"id" => 744, "name" => "charlie chambers", "cardtype" => "Gold", "approved" => true, "api_id" => "mu3qfqpfxw3mvhrigolr", "season" => 23})
OriginalCard.create!({"id" => 745, "name" => "dina skovgaard", "cardtype" => "Gold", "approved" => true, "api_id" => "ixiymacbvzdavdpdq4cf", "season" => 23})
OriginalCard.create!({"id" => 746, "name" => "dom patterson", "cardtype" => "Gold", "approved" => true, "api_id" => "dfxlbzddd4luhwu8shlw", "season" => 23})
OriginalCard.create!({"id" => 747, "name" => "dunkler somerwine", "cardtype" => "Gold", "approved" => true, "api_id" => "hmzwhdbir6griw8r7aah", "season" => 23})
OriginalCard.create!({"id" => 748, "name" => "eric belmont", "cardtype" => "Gold", "approved" => true, "api_id" => "g1jdokgxzrzfd1vkbsle", "season" => 23})
OriginalCard.create!({"id" => 749, "name" => "jakob fensterhausen", "cardtype" => "Gold", "approved" => true, "api_id" => "lclg32qylhmm3hb2wcgz", "season" => 23})
OriginalCard.create!({"id" => 750, "name" => "james asprey", "cardtype" => "Gold", "approved" => true, "api_id" => "n2qexmnwf38izkslusuo", "season" => 23})
OriginalCard.create!({"id" => 751, "name" => "jude greer", "cardtype" => "Gold", "approved" => true, "api_id" => "g5xptiigghlak2wasmcx", "season" => 23})
OriginalCard.create!({"id" => 752, "name" => "kurt lightning", "cardtype" => "Gold", "approved" => true, "api_id" => "c2hroabsmp43w3oulr0f", "season" => 23})
OriginalCard.create!({"id" => 753, "name" => "leandro dybala", "cardtype" => "Gold", "approved" => true, "api_id" => "pxxzvikcijrsgdccl323", "season" => 23})
OriginalCard.create!({"id" => 754, "name" => "louis ashworth", "cardtype" => "Gold", "approved" => true, "api_id" => "xe4gwo59lmztw0tpsewr", "season" => 23})
OriginalCard.create!({"id" => 755, "name" => "mikko rashford ii", "cardtype" => "Gold", "approved" => true, "api_id" => "gbfq6f0ohehsozbtvgwj", "season" => 23})
OriginalCard.create!({"id" => 756, "name" => "misagh khabiri", "cardtype" => "Gold", "approved" => true, "api_id" => "oxpt0qqx1wa7qjfbb2ki", "season" => 23})
OriginalCard.create!({"id" => 757, "name" => "nikolai ahmed", "cardtype" => "Gold", "approved" => true, "api_id" => "qhhl5izzg61b1t27mcrl", "season" => 23})
OriginalCard.create!({"id" => 758, "name" => "pablo kawasaki", "cardtype" => "Gold", "approved" => true, "api_id" => "mfgsy6u2phz7svbptaoa", "season" => 23})
OriginalCard.create!({"id" => 759, "name" => "pete martell", "cardtype" => "Gold", "approved" => true, "api_id" => "cq94ne4m4ns5ilyig4sw", "season" => 23})
OriginalCard.create!({"id" => 760, "name" => "ryan kirkpatrick", "cardtype" => "Gold", "approved" => true, "api_id" => "xyxjk5vqvjatlmk30pil", "season" => 23})
OriginalCard.create!({"id" => 761, "name" => "santos neymarinho", "cardtype" => "Gold", "approved" => true, "api_id" => "iroldkddmuie3c1ik5qd", "season" => 23})
OriginalCard.create!({"id" => 762, "name" => "squidward tortellini", "cardtype" => "Gold", "approved" => true, "api_id" => "zvcg6y4gk6ephnyyg7ih", "season" => 23})
OriginalCard.create!({"id" => 763, "name" => "steven urkel", "cardtype" => "Gold", "approved" => true, "api_id" => "ebfy4ysxnjn5irkkqgba", "season" => 23})
OriginalCard.create!({"id" => 764, "name" => "yoma hashimoto", "cardtype" => "Gold", "approved" => true, "api_id" => "fsarflv77k9mqikyhbmd", "season" => 23})
OriginalCard.create!({"id" => 765, "name" => "dogwood maple", "cardtype" => "Bronze", "approved" => true, "api_id" => "tdw9gsufmfstk8dnhxg1", "season" => 23})
OriginalCard.create!({"id" => 766, "name" => "tony yeboah", "cardtype" => "Bronze", "approved" => true, "api_id" => "dmnxtpidolqi8kawctiq", "season" => 23})
OriginalCard.create!({"id" => 767, "name" => "heather bull", "cardtype" => "Bronze", "approved" => true, "api_id" => "zoz2ipog7v2vz3ey34yk", "season" => 23})
OriginalCard.create!({"id" => 768, "name" => "tyson nunez", "cardtype" => "Bronze", "approved" => true, "api_id" => "fmkqozefqbjqwwigr26i", "season" => 23})
OriginalCard.create!({"id" => 769, "name" => "pascal anivierre", "cardtype" => "Bronze", "approved" => true, "api_id" => "mblyt0ojaeqx0uyiy7tc", "season" => 23})
OriginalCard.create!({"id" => 770, "name" => "victor howell", "cardtype" => "Bronze", "approved" => true, "api_id" => "xwgec8ymcaevtumv1p9p", "season" => 23})
OriginalCard.create!({"id" => 771, "name" => "billy bobby", "cardtype" => "Bronze", "approved" => true, "api_id" => "rwxea2nqiystslcxzm5a", "season" => 23})
OriginalCard.create!({"id" => 772, "name" => nil, "cardtype" => "Bronze", "approved" => true, "api_id" => "dtvv01dtvgugf7iilo02", "season" => 23})
OriginalCard.create!({"id" => 773, "name" => "fabian fischer", "cardtype" => "Bronze", "approved" => true, "api_id" => "jyfflqqs9nyrntswbilf", "season" => 23})
OriginalCard.create!({"id" => 774, "name" => "emiliano yoichi isagi", "cardtype" => "Bronze", "approved" => true, "api_id" => "dmxnbf8epn333lugiuod", "season" => 23})
OriginalCard.create!({"id" => 775, "name" => "connor reed", "cardtype" => "Bronze", "approved" => true, "api_id" => "wbiexrywcswhz0vjtykq", "season" => 23})
OriginalCard.create!({"id" => 776, "name" => "leif physt", "cardtype" => "Bronze", "approved" => true, "api_id" => "cd17hegyltvlmuakdmtn", "season" => 23})
OriginalCard.create!({"id" => 777, "name" => "miguel alves", "cardtype" => "Bronze", "approved" => true, "api_id" => "ojyipsl9wecd7t2cj03v", "season" => 23})
OriginalCard.create!({"id" => 778, "name" => "aimo talli", "cardtype" => "Bronze", "approved" => true, "api_id" => "vw9tbyrgwg6t3m4lyjxt", "season" => 23})
OriginalCard.create!({"id" => 779, "name" => "lui kemoeatu", "cardtype" => "Bronze", "approved" => true, "api_id" => "kemulg6s67m67r5tfjt8", "season" => 23})
OriginalCard.create!({"id" => 780, "name" => "guillaume olivier aubuchon touchette", "cardtype" => "Bronze", "approved" => true, "api_id" => "tzlwzsmlii8pp5doooa5", "season" => 23})
OriginalCard.create!({"id" => 781, "name" => "seth mcneil", "cardtype" => "Bronze", "approved" => true, "api_id" => "olev6uu6awomm05cmygl", "season" => 23})
OriginalCard.create!({"id" => 782, "name" => "jay bryzski", "cardtype" => "Bronze", "approved" => true, "api_id" => "ucku7d4ggjb8lm5ztk2k", "season" => 23})
OriginalCard.create!({"id" => 783, "name" => "tata youre", "cardtype" => "Bronze", "approved" => true, "api_id" => "xywxrm53eol4tbw9wtas", "season" => 23})
OriginalCard.create!({"id" => 784, "name" => "bob divesinalot", "cardtype" => "Bronze", "approved" => true, "api_id" => "bqux664nilylmhfsprln", "season" => 23})
OriginalCard.create!({"id" => 785, "name" => "abdoulaye camavinga", "cardtype" => "Bronze", "approved" => true, "api_id" => "iux7hubihhxvmkxwnue7", "season" => 23})
OriginalCard.create!({"id" => 786, "name" => "luke walker", "cardtype" => "Bronze", "approved" => true, "api_id" => "nivxzhoglit76pneazrt", "season" => 23})
OriginalCard.create!({"id" => 787, "name" => "borey barflett", "cardtype" => "Bronze", "approved" => true, "api_id" => "z51bkgavfcrzowhcjioa", "season" => 23})
OriginalCard.create!({"id" => 788, "name" => "ask jeeves", "cardtype" => "Bronze", "approved" => true, "api_id" => "lukgbao2jqdfsjgqme1f", "season" => 23})
OriginalCard.create!({"id" => 789, "name" => "scott macleod", "cardtype" => "Bronze", "approved" => true, "api_id" => "fckeuxcgyg2z4sgb0aqd", "season" => 23})
OriginalCard.create!({"id" => 790, "name" => "adi gohil", "cardtype" => "Bronze", "approved" => true, "api_id" => "owpm38zcuj2ibwlw0ust", "season" => 23})
OriginalCard.create!({"id" => 791, "name" => "hans grudnar", "cardtype" => "Bronze", "approved" => true, "api_id" => "v9c9o0qqjdyqd8wizdbf", "season" => 23})
OriginalCard.create!({"id" => 792, "name" => "mike rup", "cardtype" => "Bronze", "approved" => true, "api_id" => "c5vpzxdmxqdocagibudu", "season" => 23})
OriginalCard.create!({"id" => 793, "name" => "monkey buccaneer", "cardtype" => "Bronze", "approved" => true, "api_id" => "hrrboadaqjojou6yvmna", "season" => 23})
OriginalCard.create!({"id" => 794, "name" => "vins vins", "cardtype" => "Bronze", "approved" => true, "api_id" => "ruxtd8dcjxjg3c5ys5nx", "season" => 23})
OriginalCard.create!({"id" => 795, "name" => "dimitrios karras", "cardtype" => "Bronze", "approved" => true, "api_id" => "zpngauw24br6bexdwhc2", "season" => 23})
OriginalCard.create!({"id" => 796, "name" => "volkan kiziltas", "cardtype" => "Bronze", "approved" => true, "api_id" => "cu1hzxmloxrwfur35xbn", "season" => 23})
OriginalCard.create!({"id" => 797, "name" => "miguel oliveira", "cardtype" => "Bronze", "approved" => true, "api_id" => "n9d0eoo3d7ni0aclctmc", "season" => 23})
OriginalCard.create!({"id" => 798, "name" => "henrik lind", "cardtype" => "Bronze", "approved" => true, "api_id" => "cvu14htg8su8uzwn9fil", "season" => 23})
OriginalCard.create!({"id" => 799, "name" => "helena soderberg", "cardtype" => "Bronze", "approved" => true, "api_id" => "rbesfab3l74eti8btznb", "season" => 23})
OriginalCard.create!({"id" => 800, "name" => "nico grimes", "cardtype" => "Bronze", "approved" => true, "api_id" => "rnblyopum08z1svjjbdj", "season" => 23})
OriginalCard.create!({"id" => 801, "name" => "jiang you", "cardtype" => "Bronze", "approved" => true, "api_id" => "ouwm6ynzqdecbtatwuhu", "season" => 23})
OriginalCard.create!({"id" => 802, "name" => "jannik andersen", "cardtype" => "Bronze", "approved" => true, "api_id" => "f7svpuxsh3y4tzs0kard", "season" => 23})
OriginalCard.create!({"id" => 803, "name" => "john faxe kondi", "cardtype" => "Bronze", "approved" => true, "api_id" => "p5nk2qyf1fg3uaewn3ds", "season" => 23})
OriginalCard.create!({"id" => 804, "name" => "tom pedersen", "cardtype" => "Bronze", "approved" => true, "api_id" => "ghll3gevqzcz3db5sidz", "season" => 23})
OriginalCard.create!({"id" => 805, "name" => "pujan kothari", "cardtype" => "Bronze", "approved" => true, "api_id" => "opwmm5wxxhqmfzloteqb", "season" => 23})
OriginalCard.create!({"id" => 806, "name" => "dorian lexington", "cardtype" => "Bronze", "approved" => true, "api_id" => "jb1llemdhndiyafzv1wu", "season" => 23})
OriginalCard.create!({"id" => 807, "name" => "danny michati", "cardtype" => "Bronze", "approved" => true, "api_id" => "qunjorh1tvxofqxsftzx", "season" => 23})
OriginalCard.create!({"id" => 808, "name" => "kaspar talvik", "cardtype" => "Bronze", "approved" => true, "api_id" => "mkttbvkmbq4zytughf1x", "season" => 23})
OriginalCard.create!({"id" => 809, "name" => "kaspars kalinins", "cardtype" => "Bronze", "approved" => true, "api_id" => "s1r80aorwrmumqs9zk2f", "season" => 23})
OriginalCard.create!({"id" => 810, "name" => "pardner magool", "cardtype" => "Bronze", "approved" => true, "api_id" => "mphdrtudybxj285x891k", "season" => 23})
OriginalCard.create!({"id" => 811, "name" => "david brukspatron", "cardtype" => "Bronze", "approved" => true, "api_id" => "fcqurgmnyjzmdybscevs", "season" => 23})
OriginalCard.create!({"id" => 812, "name" => "dwayne pruney", "cardtype" => "Bronze", "approved" => true, "api_id" => "eidj8jvjjpvkyb0riozl", "season" => 23})
OriginalCard.create!({"id" => 813, "name" => "aren fjord", "cardtype" => "Bronze", "approved" => true, "api_id" => "wftsparnhiikrm9oujam", "season" => 23})
OriginalCard.create!({"id" => 814, "name" => "cong minh dao", "cardtype" => "Bronze", "approved" => true, "api_id" => "kpy1ta2grxkkgjz5mq7x", "season" => 23})
OriginalCard.create!({"id" => 815, "name" => "hugh mann", "cardtype" => "Bronze", "approved" => true, "api_id" => "zsk4viunnblhizlus0da", "season" => 23})
OriginalCard.create!({"id" => 816, "name" => "ricky bobby", "cardtype" => "Bronze", "approved" => true, "api_id" => "xft0xoactj94mj9qxcqe", "season" => 23})
OriginalCard.create!({"id" => 817, "name" => "juha jarvinen", "cardtype" => "Bronze", "approved" => true, "api_id" => "rrggirubay2rxhhic18w", "season" => 23})
OriginalCard.create!({"id" => 818, "name" => "weston mcnuggie", "cardtype" => "Bronze", "approved" => true, "api_id" => "gxxho2gleblt7vzenzgl", "season" => 23})
OriginalCard.create!({"id" => 819, "name" => "cole mertz", "cardtype" => "Bronze", "approved" => true, "api_id" => "fz2uxide0hyydml59fpr", "season" => 23})
OriginalCard.create!({"id" => 820, "name" => "thomas schwarte", "cardtype" => "Bronze", "approved" => true, "api_id" => "unez4dn6lce9laeeonlc", "season" => 23})
OriginalCard.create!({"id" => 821, "name" => "donna rumma", "cardtype" => "Bronze", "approved" => true, "api_id" => "yotvonuqpnsc63lccrlt", "season" => 23})
OriginalCard.create!({"id" => 822, "name" => "yannick visser", "cardtype" => "Bronze", "approved" => true, "api_id" => "fcimkvxc7gcyssdqekff", "season" => 23})
OriginalCard.create!({"id" => 823, "name" => "sky scraper", "cardtype" => "Bronze", "approved" => true, "api_id" => "xcjzztzp0p6ega4pwate", "season" => 23})
OriginalCard.create!({"id" => 824, "name" => "zinedine gintonic", "cardtype" => "Bronze", "approved" => true, "api_id" => "hgviozlakevtvnr5etvi", "season" => 23})
OriginalCard.create!({"id" => 825, "name" => "mikko rashford", "cardtype" => "Bronze", "approved" => true, "api_id" => "zcwz0ffrsmgq0nm6b3jq", "season" => 23})
OriginalCard.create!({"id" => 826, "name" => "matt oopsie wrongsport turk", "cardtype" => "Bronze", "approved" => true, "api_id" => "roxr1azvbiyhvwetec3b", "season" => 23})
OriginalCard.create!({"id" => 827, "name" => "rean schwarzer", "cardtype" => "Bronze", "approved" => true, "api_id" => "uveukr2krbxdcoljtept", "season" => 23})
OriginalCard.create!({"id" => 828, "name" => "arsene ngoussou", "cardtype" => "Bronze", "approved" => true, "api_id" => "ovoqvvzwnrk6npqbhmvy", "season" => 23})
OriginalCard.create!({"id" => 829, "name" => "sydney ramirez", "cardtype" => "Bronze", "approved" => true, "api_id" => "pb6lo7ycmo2jucqhn84n", "season" => 23})
OriginalCard.create!({"id" => 830, "name" => "robbie schuurmans", "cardtype" => "Bronze", "approved" => true, "api_id" => "gphaqtsq83pjecukspsl", "season" => 23})
OriginalCard.create!({"id" => 831, "name" => "alexandra gunnarson", "cardtype" => "Bronze", "approved" => true, "api_id" => "rvjqvcbzkoi43am54tvn", "season" => 23})
OriginalCard.create!({"id" => 832, "name" => "pierre houde", "cardtype" => "Bronze", "approved" => true, "api_id" => "wfivy9n928wiuutx7a3s", "season" => 23})
OriginalCard.create!({"id" => 833, "name" => "luc van setten", "cardtype" => "Bronze", "approved" => true, "api_id" => "qcqc4ib9rgs25nt6rsvn", "season" => 23})
OriginalCard.create!({"id" => 834, "name" => "babatunde agachuthu", "cardtype" => "Bronze", "approved" => true, "api_id" => "ilxgxeldn89jr2bsk8ak", "season" => 23})
OriginalCard.create!({"id" => 835, "name" => "nico lam", "cardtype" => "Bronze", "approved" => true, "api_id" => "k9uxdsqts3twvbnrkjzv", "season" => 23})
OriginalCard.create!({"id" => 836, "name" => "squall vercetti", "cardtype" => "Bronze", "approved" => true, "api_id" => "tpybnxjpjyseww2rulb4", "season" => 23})
OriginalCard.create!({"id" => 837, "name" => "leonidas papadopoulos", "cardtype" => "Bronze", "approved" => true, "api_id" => "bnh438d3agfkatoiagym", "season" => 23})
OriginalCard.create!({"id" => 838, "name" => "lucas james", "cardtype" => "Bronze", "approved" => true, "api_id" => "yyepioqq9ytf5bkcozzx", "season" => 23})
OriginalCard.create!({"id" => 839, "name" => "jonathan munoz", "cardtype" => "Bronze", "approved" => true, "api_id" => "vqwxkxdxt1ryg63z5hsf", "season" => 23})
OriginalCard.create!({"id" => 840, "name" => "xavier simmons", "cardtype" => "Bronze", "approved" => true, "api_id" => "wh8o1chmtklyqte9qpgz", "season" => 23})
OriginalCard.create!({"id" => 841, "name" => "jokull juliusson", "cardtype" => "Bronze", "approved" => true, "api_id" => "pfnfuzhtabzdmku0xcff", "season" => 23})
OriginalCard.create!({"id" => 842, "name" => "dobby roobe", "cardtype" => "Bronze", "approved" => true, "api_id" => "oiizfmddhzyvryylk8jc", "season" => 23})
OriginalCard.create!({"id" => 843, "name" => "spack jarrow", "cardtype" => "Bronze", "approved" => true, "api_id" => "vtup7jahzyr4csj6czaz", "season" => 23})
OriginalCard.create!({"id" => 844, "name" => "franco torres", "cardtype" => "Bronze", "approved" => true, "api_id" => "im9anurhf8nlddzhprxj", "season" => 23})
OriginalCard.create!({"id" => 845, "name" => "demi perez", "cardtype" => "Bronze", "approved" => true, "api_id" => "lekqdzmercxbgaxrgvhm", "season" => 23})
OriginalCard.create!({"id" => 846, "name" => "manuel neuer", "cardtype" => "Bronze", "approved" => true, "api_id" => "ds1bgv3oqrgvaxdaj6yt", "season" => 23})
OriginalCard.create!({"id" => 847, "name" => "george costanza", "cardtype" => "Bronze", "approved" => true, "api_id" => "sh7dzff2hojd6ubmoqxc", "season" => 23})
OriginalCard.create!({"id" => 848, "name" => "miles richards", "cardtype" => "Bronze", "approved" => true, "api_id" => "bl8a1ersyq4fflndlpdt", "season" => 23})
OriginalCard.create!({"id" => 849, "name" => "ross downing", "cardtype" => "Bronze", "approved" => true, "api_id" => "kixmxmawxlneockl8tmy", "season" => 23})
OriginalCard.create!({"id" => 850, "name" => "hol lediver", "cardtype" => "Bronze", "approved" => true, "api_id" => "c3zx1gwqrrl4rreztb7l", "season" => 23})
OriginalCard.create!({"id" => 851, "name" => "zizou lopta ii", "cardtype" => "Bronze", "approved" => true, "api_id" => "djgtfwgssl2qvgj7rchl", "season" => 23})
OriginalCard.create!({"id" => 852, "name" => "johnny crying", "cardtype" => "Bronze", "approved" => true, "api_id" => "kalxbq1lx0pa55o7uuhk", "season" => 23})
OriginalCard.create!({"id" => 853, "name" => "ryan lecavalier", "cardtype" => "Bronze", "approved" => true, "api_id" => "e0gwoiiac4cbil4ftpkf", "season" => 23})
OriginalCard.create!({"id" => 854, "name" => "dr squid", "cardtype" => "Bronze", "approved" => true, "api_id" => "vxzc2owdcjok5qn9iiwu", "season" => 23})
OriginalCard.create!({"id" => 855, "name" => "jeff sausaginho", "cardtype" => "Bronze", "approved" => true, "api_id" => "fcebxlzpf1ivtv6l3uht", "season" => 23})
OriginalCard.create!({"id" => 856, "name" => "linnea nesse", "cardtype" => "Bronze", "approved" => true, "api_id" => "sxkoqp7cwpo3waxspw3s", "season" => 23})
OriginalCard.create!({"id" => 857, "name" => "ilya pautov", "cardtype" => "Bronze", "approved" => true, "api_id" => "lig6pztm7ry6pejyp43a", "season" => 23})
OriginalCard.create!({"id" => 858, "name" => "mihaila marius", "cardtype" => "Bronze", "approved" => true, "api_id" => "f6swt5flylzh7tjkpvca", "season" => 23})
OriginalCard.create!({"id" => 859, "name" => "charlie mcphee", "cardtype" => "Bronze", "approved" => true, "api_id" => "l9qho28vpzfmgkhuahsn", "season" => 23})
OriginalCard.create!({"id" => 860, "name" => "conrad maier", "cardtype" => "Bronze", "approved" => true, "api_id" => "yonmqmobdvqu8hhy81z9", "season" => 23})
OriginalCard.create!({"id" => 861, "name" => "deedee yoker", "cardtype" => "Bronze", "approved" => true, "api_id" => "gznfkf6hbv2qrgtyl0gp", "season" => 23})
OriginalCard.create!({"id" => 862, "name" => "manuel montalto", "cardtype" => "Bronze", "approved" => true, "api_id" => "imuocsdzetkrpnyqatio", "season" => 23})
OriginalCard.create!({"id" => 863, "name" => "rip van winkle", "cardtype" => "Bronze", "approved" => true, "api_id" => "klmvhw4jzdmizismij5e", "season" => 23})
OriginalCard.create!({"id" => 864, "name" => "george leemhuis", "cardtype" => "Bronze", "approved" => true, "api_id" => "b0qcwankub9zzrurxapr", "season" => 23})
OriginalCard.create!({"id" => 865, "name" => "tommaso cappellari", "cardtype" => "Bronze", "approved" => true, "api_id" => "ltjcsc0quqwoxpog8pff", "season" => 23})
OriginalCard.create!({"id" => 866, "name" => "sepp holzlmayr", "cardtype" => "Bronze", "approved" => true, "api_id" => "hoyeuqqbkomcx2gru3nw", "season" => 23})
OriginalCard.create!({"id" => 867, "name" => "wesley stains", "cardtype" => "Bronze", "approved" => true, "api_id" => "afyjwrcbarcyeiiyvjoz", "season" => 23})
OriginalCard.create!({"id" => 868, "name" => "hun possible", "cardtype" => "Bronze", "approved" => true, "api_id" => "l8syfmymnyo3lrwjtzuw", "season" => 23})
OriginalCard.create!({"id" => 869, "name" => "liang kuai", "cardtype" => "Bronze", "approved" => true, "api_id" => "nkcr5cil0dy87odsqfyh", "season" => 23})
OriginalCard.create!({"id" => 870, "name" => "lucas peioxoto", "cardtype" => "Bronze", "approved" => true, "api_id" => "iomyqtelnth7ysdvmlgj", "season" => 23})
OriginalCard.create!({"id" => 871, "name" => "felix arasov", "cardtype" => "Bronze", "approved" => true, "api_id" => "vki18rombbgnw3khtpjg", "season" => 23})
OriginalCard.create!({"id" => 872, "name" => "elmis the heretic", "cardtype" => "Bronze", "approved" => true, "api_id" => "bawasadd4uauziwewe82", "season" => 23})
OriginalCard.create!({"id" => 873, "name" => "bud lite large box mcguirk", "cardtype" => "Bronze", "approved" => true, "api_id" => "xagydeatjms4stpcysws", "season" => 23})
OriginalCard.create!({"id" => 874, "name" => "budget busquets", "cardtype" => "Bronze", "approved" => true, "api_id" => "nnzllfjomaunahq1lhgt", "season" => 23})
OriginalCard.create!({"id" => 875, "name" => "lan mandragoran", "cardtype" => "Bronze", "approved" => true, "api_id" => "vyosx4xbewctmpovpav0", "season" => 23})
OriginalCard.create!({"id" => 876, "name" => "mazeed al kazmi", "cardtype" => "Bronze", "approved" => true, "api_id" => "fxlhta5h95hftty3bfnc", "season" => 23})
OriginalCard.create!({"id" => 877, "name" => "junaito perez", "cardtype" => "Bronze", "approved" => true, "api_id" => "cq3gv8l1sbensf5i4h13", "season" => 23})
OriginalCard.create!({"id" => 878, "name" => "christian de nardo", "cardtype" => "Bronze", "approved" => true, "api_id" => "emhzh4tamhxlitxryr2x", "season" => 23})
OriginalCard.create!({"id" => 879, "name" => "tumelo letsie", "cardtype" => "Bronze", "approved" => true, "api_id" => "hxtqsjdfsjdpspeaqs9y", "season" => 23})
OriginalCard.create!({"id" => 880, "name" => "mike bassett", "cardtype" => "Bronze", "approved" => true, "api_id" => "h5wboxng1dczmdshzfoi", "season" => 23})
OriginalCard.create!({"id" => 881, "name" => "edwin van der sloth", "cardtype" => "Bronze", "approved" => true, "api_id" => "caikdaiuxzxdial5b1eq", "season" => 23})
OriginalCard.create!({"id" => 882, "name" => "caroni riveras", "cardtype" => "Bronze", "approved" => true, "api_id" => "ht8fgq9ka9gbrdgxqrgb", "season" => 23})
OriginalCard.create!({"id" => 883, "name" => "nepa paya", "cardtype" => "Bronze", "approved" => true, "api_id" => "q07uoonq0uhsz9evlfp9", "season" => 23})
OriginalCard.create!({"id" => 884, "name" => "pork tenderloin", "cardtype" => "Bronze", "approved" => true, "api_id" => "lwwxl7rprk8az7ng1i9z", "season" => 23})
OriginalCard.create!({"id" => 885, "name" => "scott sterling", "cardtype" => "Bronze", "approved" => true, "api_id" => "rr267u0rmkv0k2kfmykz", "season" => 23})
OriginalCard.create!({"id" => 886, "name" => "matthew mayhem", "cardtype" => "Bronze", "approved" => true, "api_id" => "ebb3eezrugyze0osxkox", "season" => 23})
OriginalCard.create!({"id" => 887, "name" => "gerald gerrard", "cardtype" => "Bronze", "approved" => true, "api_id" => "hhxhk8wjbidtyi7a7zow", "season" => 23})
OriginalCard.create!({"id" => 888, "name" => "nicolas inclan", "cardtype" => "Bronze", "approved" => true, "api_id" => "hooom83zkzblemjquci6", "season" => 23})
OriginalCard.create!({"id" => 889, "name" => "k clemence", "cardtype" => "Bronze", "approved" => true, "api_id" => "iwplg8ryhywlfewcolfh", "season" => 23})
OriginalCard.create!({"id" => 890, "name" => "adam knight", "cardtype" => "Bronze", "approved" => true, "api_id" => "dlzsvqomrbhemzcix8gu", "season" => 23})
OriginalCard.create!({"id" => 891, "name" => "will chamblee", "cardtype" => "Bronze", "approved" => true, "api_id" => "kivho1itd5q0mkljfl3z", "season" => 23})
OriginalCard.create!({"id" => 892, "name" => "archie lynch", "cardtype" => "Bronze", "approved" => true, "api_id" => "ctqwj1uxwilqppwfpa0t", "season" => 23})
OriginalCard.create!({"id" => 893, "name" => "freddy adu", "cardtype" => "Bronze", "approved" => true, "api_id" => "vvtoibh50eebhlvfzinl", "season" => 23})
OriginalCard.create!({"id" => 894, "name" => "jay cue jr", "cardtype" => "Bronze", "approved" => true, "api_id" => "jlt0fwtawegaazsovl4t", "season" => 23})
OriginalCard.create!({"id" => 895, "name" => "gideon norel", "cardtype" => "Bronze", "approved" => true, "api_id" => "nf5ut7ixzwsu3w2e9xte", "season" => 23})
OriginalCard.create!({"id" => 896, "name" => "bob berendsen", "cardtype" => "Bronze", "approved" => true, "api_id" => "hha6x9ijscgio1feypmq", "season" => 23})
OriginalCard.create!({"id" => 897, "name" => "matt oopsie wrongsport turk", "cardtype" => "Diamond", "approved" => true, "api_id" => "omqef1fudpb5v0vtftqt", "season" => 23})
OriginalCard.create!({"id" => 898, "name" => "john faxe kondi", "cardtype" => "Diamond", "approved" => true, "api_id" => "kk17xcqfha7gmz2gwqrh", "season" => 23})
OriginalCard.create!({"id" => 899, "name" => "arsene ngoussou", "cardtype" => "Diamond", "approved" => true, "api_id" => "ihyvhf9xkora7w1cotfi", "season" => 23})
OriginalCard.create!({"id" => 900, "name" => "lucas james", "cardtype" => "Diamond", "approved" => true, "api_id" => "xlzyufbhii9jsdqbq1i9", "season" => 23})
OriginalCard.create!({"id" => 901, "name" => "manuel montalto", "cardtype" => "Silver", "approved" => true, "api_id" => "i4n0mjnw9rvpzdri6wyf", "season" => 23})
OriginalCard.create!({"id" => 902, "name" => "hans grudnar", "cardtype" => "Diamond", "approved" => true, "api_id" => "yriwrispavkteipgmjlh", "season" => 23})
OriginalCard.create!({"id" => 903, "name" => "billy bobby", "cardtype" => "Silver", "approved" => true, "api_id" => "m1ohzlaj8z0ajnl2c65x", "season" => 23})
OriginalCard.create!({"id" => 904, "name" => "caroni riveras", "cardtype" => "Diamond", "approved" => true, "api_id" => "hgxb8h9rawwafqykbkt3", "season" => 23})
OriginalCard.create!({"id" => 905, "name" => "babatunde agachuthu", "cardtype" => "Silver", "approved" => true, "api_id" => "wcwk8bz5easxucvgkbbe", "season" => 23})
OriginalCard.create!({"id" => 906, "name" => "arsene ngoussou", "cardtype" => "Silver", "approved" => true, "api_id" => "kslmtcn0yazuvpczotzf", "season" => 23})
OriginalCard.create!({"id" => 907, "name" => "seth mcneil", "cardtype" => "Silver", "approved" => true, "api_id" => "bnknhy18f8fqzvmwmca1", "season" => 23})
OriginalCard.create!({"id" => 908, "name" => "freddy adu", "cardtype" => "Silver", "approved" => true, "api_id" => "tasbkpqhx2w2jyvjxyje", "season" => 23})
OriginalCard.create!({"id" => 909, "name" => "lucas james", "cardtype" => "Silver", "approved" => true, "api_id" => "wlvobtroxxef9pb5njw5", "season" => 23})
OriginalCard.create!({"id" => 910, "name" => "caroni riveras", "cardtype" => "Silver", "approved" => true, "api_id" => "tyipgdlwwiofzz7mism3", "season" => 23})
OriginalCard.create!({"id" => 911, "name" => "thomas schwarte", "cardtype" => "Silver", "approved" => true, "api_id" => "n30x51yhdvrtquexi1cu", "season" => 23})
OriginalCard.create!({"id" => 912, "name" => "heung min smalls", "cardtype" => "Silver", "approved" => true, "api_id" => "nfvtnda6uckdjeq0ztft", "season" => 23})
OriginalCard.create!({"id" => 913, "name" => "rosetti moretti", "cardtype" => "Silver", "approved" => true, "api_id" => "p292vsesiy7o8vrskpvo", "season" => 23})
OriginalCard.create!({"id" => 914, "name" => "siddhartha kilgannon", "cardtype" => "Silver", "approved" => true, "api_id" => "fifwnxlf7rnjvtwbyvot", "season" => 23})
OriginalCard.create!({"id" => 915, "name" => "mikko rashford iv", "cardtype" => "Silver", "approved" => true, "api_id" => "wpybouixvh1fexgqmfcw", "season" => 23})
OriginalCard.create!({"id" => 916, "name" => "bryvins mbeumo", "cardtype" => "Silver", "approved" => true, "api_id" => "ck7zb3skbkbbebfq0b7w", "season" => 23})
OriginalCard.create!({"id" => 917, "name" => "joseph mathys hendry", "cardtype" => "Silver", "approved" => true, "api_id" => "ytlwllrscojkhiwwp1bz", "season" => 23})
OriginalCard.create!({"id" => 918, "name" => "wu lei", "cardtype" => "Silver", "approved" => true, "api_id" => "dqsi9c4nnmn25wbbaraa", "season" => 23})
OriginalCard.create!({"id" => 919, "name" => "zizou lopta ii", "cardtype" => "Silver", "approved" => true, "api_id" => "ucpro2w6bbkfhlb4ak4d", "season" => 23})
OriginalCard.create!({"id" => 920, "name" => "matt oopsie wrongsport turk", "cardtype" => "Silver", "approved" => true, "api_id" => "yzikl6tkgyimzffaprcq", "season" => 23})
OriginalCard.create!({"id" => 921, "name" => "minh dao cong", "cardtype" => "Silver", "approved" => true, "api_id" => "lqvbuth7mvrxpsxpdtio", "season" => 23})
OriginalCard.create!({"id" => 922, "name" => "jose dias", "cardtype" => "Silver", "approved" => true, "api_id" => "pgvio4mwa9ldkpve4isq", "season" => 23})
OriginalCard.create!({"id" => 923, "name" => "nyron nosworthy", "cardtype" => "Silver", "approved" => true, "api_id" => "kvalvgdnuord4jfdurad", "season" => 23})
OriginalCard.create!({"id" => 924, "name" => "alejandro fuecoco", "cardtype" => "Silver", "approved" => true, "api_id" => "gwwb4k2tanf45t0ps5zq", "season" => 23})
OriginalCard.create!({"id" => 925, "name" => "matt oopsie wrongsport turk", "cardtype" => "Silver", "approved" => true, "api_id" => "rar7hsi3q8i164hldsga", "season" => 23})
OriginalCard.create!({"id" => 926, "name" => "gianlugia buffoon", "cardtype" => "Silver", "approved" => true, "api_id" => "vuaryhxv7wgvpwlkylkd", "season" => 23})
OriginalCard.create!({"id" => 927, "name" => "beelze bot", "cardtype" => "Silver", "approved" => true, "api_id" => "hymkcuzuuydmjshrl9k8", "season" => 23})
